require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Coin2sController do

  # This should return the minimal set of attributes required to create a valid
  # Coin2. As you add validations to Coin2, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Coin2sController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all coin2s as @coin2s" do
      coin2 = Coin2.create! valid_attributes
      get :index, {}, valid_session
      assigns(:coin2s).should eq([coin2])
    end
  end

  describe "GET show" do
    it "assigns the requested coin2 as @coin2" do
      coin2 = Coin2.create! valid_attributes
      get :show, {:id => coin2.to_param}, valid_session
      assigns(:coin2).should eq(coin2)
    end
  end

  describe "GET new" do
    it "assigns a new coin2 as @coin2" do
      get :new, {}, valid_session
      assigns(:coin2).should be_a_new(Coin2)
    end
  end

  describe "GET edit" do
    it "assigns the requested coin2 as @coin2" do
      coin2 = Coin2.create! valid_attributes
      get :edit, {:id => coin2.to_param}, valid_session
      assigns(:coin2).should eq(coin2)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Coin2" do
        expect {
          post :create, {:coin2 => valid_attributes}, valid_session
        }.to change(Coin2, :count).by(1)
      end

      it "assigns a newly created coin2 as @coin2" do
        post :create, {:coin2 => valid_attributes}, valid_session
        assigns(:coin2).should be_a(Coin2)
        assigns(:coin2).should be_persisted
      end

      it "redirects to the created coin2" do
        post :create, {:coin2 => valid_attributes}, valid_session
        response.should redirect_to(Coin2.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved coin2 as @coin2" do
        # Trigger the behavior that occurs when invalid params are submitted
        Coin2.any_instance.stub(:save).and_return(false)
        post :create, {:coin2 => {}}, valid_session
        assigns(:coin2).should be_a_new(Coin2)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Coin2.any_instance.stub(:save).and_return(false)
        post :create, {:coin2 => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested coin2" do
        coin2 = Coin2.create! valid_attributes
        # Assuming there are no other coin2s in the database, this
        # specifies that the Coin2 created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Coin2.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => coin2.to_param, :coin2 => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested coin2 as @coin2" do
        coin2 = Coin2.create! valid_attributes
        put :update, {:id => coin2.to_param, :coin2 => valid_attributes}, valid_session
        assigns(:coin2).should eq(coin2)
      end

      it "redirects to the coin2" do
        coin2 = Coin2.create! valid_attributes
        put :update, {:id => coin2.to_param, :coin2 => valid_attributes}, valid_session
        response.should redirect_to(coin2)
      end
    end

    describe "with invalid params" do
      it "assigns the coin2 as @coin2" do
        coin2 = Coin2.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Coin2.any_instance.stub(:save).and_return(false)
        put :update, {:id => coin2.to_param, :coin2 => {}}, valid_session
        assigns(:coin2).should eq(coin2)
      end

      it "re-renders the 'edit' template" do
        coin2 = Coin2.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Coin2.any_instance.stub(:save).and_return(false)
        put :update, {:id => coin2.to_param, :coin2 => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested coin2" do
      coin2 = Coin2.create! valid_attributes
      expect {
        delete :destroy, {:id => coin2.to_param}, valid_session
      }.to change(Coin2, :count).by(-1)
    end

    it "redirects to the coin2s list" do
      coin2 = Coin2.create! valid_attributes
      delete :destroy, {:id => coin2.to_param}, valid_session
      response.should redirect_to(coin2s_url)
    end
  end

end
