require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CoinAttributeTypesController do

  # This should return the minimal set of attributes required to create a valid
  # CoinAttributeType. As you add validations to CoinAttributeType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CoinAttributeTypesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all coin_attribute_types as @coin_attribute_types" do
      coin_attribute_type = CoinAttributeType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:coin_attribute_types).should eq([coin_attribute_type])
    end
  end

  describe "GET show" do
    it "assigns the requested coin_attribute_type as @coin_attribute_type" do
      coin_attribute_type = CoinAttributeType.create! valid_attributes
      get :show, {:id => coin_attribute_type.to_param}, valid_session
      assigns(:coin_attribute_type).should eq(coin_attribute_type)
    end
  end

  describe "GET new" do
    it "assigns a new coin_attribute_type as @coin_attribute_type" do
      get :new, {}, valid_session
      assigns(:coin_attribute_type).should be_a_new(CoinAttributeType)
    end
  end

  describe "GET edit" do
    it "assigns the requested coin_attribute_type as @coin_attribute_type" do
      coin_attribute_type = CoinAttributeType.create! valid_attributes
      get :edit, {:id => coin_attribute_type.to_param}, valid_session
      assigns(:coin_attribute_type).should eq(coin_attribute_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CoinAttributeType" do
        expect {
          post :create, {:coin_attribute_type => valid_attributes}, valid_session
        }.to change(CoinAttributeType, :count).by(1)
      end

      it "assigns a newly created coin_attribute_type as @coin_attribute_type" do
        post :create, {:coin_attribute_type => valid_attributes}, valid_session
        assigns(:coin_attribute_type).should be_a(CoinAttributeType)
        assigns(:coin_attribute_type).should be_persisted
      end

      it "redirects to the created coin_attribute_type" do
        post :create, {:coin_attribute_type => valid_attributes}, valid_session
        response.should redirect_to(CoinAttributeType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved coin_attribute_type as @coin_attribute_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        CoinAttributeType.any_instance.stub(:save).and_return(false)
        post :create, {:coin_attribute_type => {}}, valid_session
        assigns(:coin_attribute_type).should be_a_new(CoinAttributeType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CoinAttributeType.any_instance.stub(:save).and_return(false)
        post :create, {:coin_attribute_type => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested coin_attribute_type" do
        coin_attribute_type = CoinAttributeType.create! valid_attributes
        # Assuming there are no other coin_attribute_types in the database, this
        # specifies that the CoinAttributeType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CoinAttributeType.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => coin_attribute_type.to_param, :coin_attribute_type => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested coin_attribute_type as @coin_attribute_type" do
        coin_attribute_type = CoinAttributeType.create! valid_attributes
        put :update, {:id => coin_attribute_type.to_param, :coin_attribute_type => valid_attributes}, valid_session
        assigns(:coin_attribute_type).should eq(coin_attribute_type)
      end

      it "redirects to the coin_attribute_type" do
        coin_attribute_type = CoinAttributeType.create! valid_attributes
        put :update, {:id => coin_attribute_type.to_param, :coin_attribute_type => valid_attributes}, valid_session
        response.should redirect_to(coin_attribute_type)
      end
    end

    describe "with invalid params" do
      it "assigns the coin_attribute_type as @coin_attribute_type" do
        coin_attribute_type = CoinAttributeType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CoinAttributeType.any_instance.stub(:save).and_return(false)
        put :update, {:id => coin_attribute_type.to_param, :coin_attribute_type => {}}, valid_session
        assigns(:coin_attribute_type).should eq(coin_attribute_type)
      end

      it "re-renders the 'edit' template" do
        coin_attribute_type = CoinAttributeType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CoinAttributeType.any_instance.stub(:save).and_return(false)
        put :update, {:id => coin_attribute_type.to_param, :coin_attribute_type => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested coin_attribute_type" do
      coin_attribute_type = CoinAttributeType.create! valid_attributes
      expect {
        delete :destroy, {:id => coin_attribute_type.to_param}, valid_session
      }.to change(CoinAttributeType, :count).by(-1)
    end

    it "redirects to the coin_attribute_types list" do
      coin_attribute_type = CoinAttributeType.create! valid_attributes
      delete :destroy, {:id => coin_attribute_type.to_param}, valid_session
      response.should redirect_to(coin_attribute_types_url)
    end
  end

end
