require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MintCoinsController do

  # This should return the minimal set of attributes required to create a valid
  # MintCoin. As you add validations to MintCoin, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MintCoinsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all mint_coins as @mint_coins" do
      mint_coin = MintCoin.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mint_coins).should eq([mint_coin])
    end
  end

  describe "GET show" do
    it "assigns the requested mint_coin as @mint_coin" do
      mint_coin = MintCoin.create! valid_attributes
      get :show, {:id => mint_coin.to_param}, valid_session
      assigns(:mint_coin).should eq(mint_coin)
    end
  end

  describe "GET new" do
    it "assigns a new mint_coin as @mint_coin" do
      get :new, {}, valid_session
      assigns(:mint_coin).should be_a_new(MintCoin)
    end
  end

  describe "GET edit" do
    it "assigns the requested mint_coin as @mint_coin" do
      mint_coin = MintCoin.create! valid_attributes
      get :edit, {:id => mint_coin.to_param}, valid_session
      assigns(:mint_coin).should eq(mint_coin)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MintCoin" do
        expect {
          post :create, {:mint_coin => valid_attributes}, valid_session
        }.to change(MintCoin, :count).by(1)
      end

      it "assigns a newly created mint_coin as @mint_coin" do
        post :create, {:mint_coin => valid_attributes}, valid_session
        assigns(:mint_coin).should be_a(MintCoin)
        assigns(:mint_coin).should be_persisted
      end

      it "redirects to the created mint_coin" do
        post :create, {:mint_coin => valid_attributes}, valid_session
        response.should redirect_to(MintCoin.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mint_coin as @mint_coin" do
        # Trigger the behavior that occurs when invalid params are submitted
        MintCoin.any_instance.stub(:save).and_return(false)
        post :create, {:mint_coin => {}}, valid_session
        assigns(:mint_coin).should be_a_new(MintCoin)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MintCoin.any_instance.stub(:save).and_return(false)
        post :create, {:mint_coin => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mint_coin" do
        mint_coin = MintCoin.create! valid_attributes
        # Assuming there are no other mint_coins in the database, this
        # specifies that the MintCoin created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MintCoin.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => mint_coin.to_param, :mint_coin => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested mint_coin as @mint_coin" do
        mint_coin = MintCoin.create! valid_attributes
        put :update, {:id => mint_coin.to_param, :mint_coin => valid_attributes}, valid_session
        assigns(:mint_coin).should eq(mint_coin)
      end

      it "redirects to the mint_coin" do
        mint_coin = MintCoin.create! valid_attributes
        put :update, {:id => mint_coin.to_param, :mint_coin => valid_attributes}, valid_session
        response.should redirect_to(mint_coin)
      end
    end

    describe "with invalid params" do
      it "assigns the mint_coin as @mint_coin" do
        mint_coin = MintCoin.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MintCoin.any_instance.stub(:save).and_return(false)
        put :update, {:id => mint_coin.to_param, :mint_coin => {}}, valid_session
        assigns(:mint_coin).should eq(mint_coin)
      end

      it "re-renders the 'edit' template" do
        mint_coin = MintCoin.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MintCoin.any_instance.stub(:save).and_return(false)
        put :update, {:id => mint_coin.to_param, :mint_coin => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mint_coin" do
      mint_coin = MintCoin.create! valid_attributes
      expect {
        delete :destroy, {:id => mint_coin.to_param}, valid_session
      }.to change(MintCoin, :count).by(-1)
    end

    it "redirects to the mint_coins list" do
      mint_coin = MintCoin.create! valid_attributes
      delete :destroy, {:id => mint_coin.to_param}, valid_session
      response.should redirect_to(mint_coins_url)
    end
  end

end
