require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MintDatesController do

  # This should return the minimal set of attributes required to create a valid
  # MintDate. As you add validations to MintDate, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MintDatesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all mint_dates as @mint_dates" do
      mint_date = MintDate.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mint_dates).should eq([mint_date])
    end
  end

  describe "GET show" do
    it "assigns the requested mint_date as @mint_date" do
      mint_date = MintDate.create! valid_attributes
      get :show, {:id => mint_date.to_param}, valid_session
      assigns(:mint_date).should eq(mint_date)
    end
  end

  describe "GET new" do
    it "assigns a new mint_date as @mint_date" do
      get :new, {}, valid_session
      assigns(:mint_date).should be_a_new(MintDate)
    end
  end

  describe "GET edit" do
    it "assigns the requested mint_date as @mint_date" do
      mint_date = MintDate.create! valid_attributes
      get :edit, {:id => mint_date.to_param}, valid_session
      assigns(:mint_date).should eq(mint_date)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MintDate" do
        expect {
          post :create, {:mint_date => valid_attributes}, valid_session
        }.to change(MintDate, :count).by(1)
      end

      it "assigns a newly created mint_date as @mint_date" do
        post :create, {:mint_date => valid_attributes}, valid_session
        assigns(:mint_date).should be_a(MintDate)
        assigns(:mint_date).should be_persisted
      end

      it "redirects to the created mint_date" do
        post :create, {:mint_date => valid_attributes}, valid_session
        response.should redirect_to(MintDate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mint_date as @mint_date" do
        # Trigger the behavior that occurs when invalid params are submitted
        MintDate.any_instance.stub(:save).and_return(false)
        post :create, {:mint_date => {}}, valid_session
        assigns(:mint_date).should be_a_new(MintDate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MintDate.any_instance.stub(:save).and_return(false)
        post :create, {:mint_date => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mint_date" do
        mint_date = MintDate.create! valid_attributes
        # Assuming there are no other mint_dates in the database, this
        # specifies that the MintDate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MintDate.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => mint_date.to_param, :mint_date => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested mint_date as @mint_date" do
        mint_date = MintDate.create! valid_attributes
        put :update, {:id => mint_date.to_param, :mint_date => valid_attributes}, valid_session
        assigns(:mint_date).should eq(mint_date)
      end

      it "redirects to the mint_date" do
        mint_date = MintDate.create! valid_attributes
        put :update, {:id => mint_date.to_param, :mint_date => valid_attributes}, valid_session
        response.should redirect_to(mint_date)
      end
    end

    describe "with invalid params" do
      it "assigns the mint_date as @mint_date" do
        mint_date = MintDate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MintDate.any_instance.stub(:save).and_return(false)
        put :update, {:id => mint_date.to_param, :mint_date => {}}, valid_session
        assigns(:mint_date).should eq(mint_date)
      end

      it "re-renders the 'edit' template" do
        mint_date = MintDate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MintDate.any_instance.stub(:save).and_return(false)
        put :update, {:id => mint_date.to_param, :mint_date => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mint_date" do
      mint_date = MintDate.create! valid_attributes
      expect {
        delete :destroy, {:id => mint_date.to_param}, valid_session
      }.to change(MintDate, :count).by(-1)
    end

    it "redirects to the mint_dates list" do
      mint_date = MintDate.create! valid_attributes
      delete :destroy, {:id => mint_date.to_param}, valid_session
      response.should redirect_to(mint_dates_url)
    end
  end

end
