require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PreciousMetalsController do

  # This should return the minimal set of attributes required to create a valid
  # PreciousMetal. As you add validations to PreciousMetal, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PreciousMetalsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all precious_metals as @precious_metals" do
      precious_metal = PreciousMetal.create! valid_attributes
      get :index, {}, valid_session
      assigns(:precious_metals).should eq([precious_metal])
    end
  end

  describe "GET show" do
    it "assigns the requested precious_metal as @precious_metal" do
      precious_metal = PreciousMetal.create! valid_attributes
      get :show, {:id => precious_metal.to_param}, valid_session
      assigns(:precious_metal).should eq(precious_metal)
    end
  end

  describe "GET new" do
    it "assigns a new precious_metal as @precious_metal" do
      get :new, {}, valid_session
      assigns(:precious_metal).should be_a_new(PreciousMetal)
    end
  end

  describe "GET edit" do
    it "assigns the requested precious_metal as @precious_metal" do
      precious_metal = PreciousMetal.create! valid_attributes
      get :edit, {:id => precious_metal.to_param}, valid_session
      assigns(:precious_metal).should eq(precious_metal)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PreciousMetal" do
        expect {
          post :create, {:precious_metal => valid_attributes}, valid_session
        }.to change(PreciousMetal, :count).by(1)
      end

      it "assigns a newly created precious_metal as @precious_metal" do
        post :create, {:precious_metal => valid_attributes}, valid_session
        assigns(:precious_metal).should be_a(PreciousMetal)
        assigns(:precious_metal).should be_persisted
      end

      it "redirects to the created precious_metal" do
        post :create, {:precious_metal => valid_attributes}, valid_session
        response.should redirect_to(PreciousMetal.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved precious_metal as @precious_metal" do
        # Trigger the behavior that occurs when invalid params are submitted
        PreciousMetal.any_instance.stub(:save).and_return(false)
        post :create, {:precious_metal => {}}, valid_session
        assigns(:precious_metal).should be_a_new(PreciousMetal)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PreciousMetal.any_instance.stub(:save).and_return(false)
        post :create, {:precious_metal => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested precious_metal" do
        precious_metal = PreciousMetal.create! valid_attributes
        # Assuming there are no other precious_metals in the database, this
        # specifies that the PreciousMetal created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PreciousMetal.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => precious_metal.to_param, :precious_metal => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested precious_metal as @precious_metal" do
        precious_metal = PreciousMetal.create! valid_attributes
        put :update, {:id => precious_metal.to_param, :precious_metal => valid_attributes}, valid_session
        assigns(:precious_metal).should eq(precious_metal)
      end

      it "redirects to the precious_metal" do
        precious_metal = PreciousMetal.create! valid_attributes
        put :update, {:id => precious_metal.to_param, :precious_metal => valid_attributes}, valid_session
        response.should redirect_to(precious_metal)
      end
    end

    describe "with invalid params" do
      it "assigns the precious_metal as @precious_metal" do
        precious_metal = PreciousMetal.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PreciousMetal.any_instance.stub(:save).and_return(false)
        put :update, {:id => precious_metal.to_param, :precious_metal => {}}, valid_session
        assigns(:precious_metal).should eq(precious_metal)
      end

      it "re-renders the 'edit' template" do
        precious_metal = PreciousMetal.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PreciousMetal.any_instance.stub(:save).and_return(false)
        put :update, {:id => precious_metal.to_param, :precious_metal => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested precious_metal" do
      precious_metal = PreciousMetal.create! valid_attributes
      expect {
        delete :destroy, {:id => precious_metal.to_param}, valid_session
      }.to change(PreciousMetal, :count).by(-1)
    end

    it "redirects to the precious_metals list" do
      precious_metal = PreciousMetal.create! valid_attributes
      delete :destroy, {:id => precious_metal.to_param}, valid_session
      response.should redirect_to(precious_metals_url)
    end
  end

end
