require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SheldonRatingScalesController do

  # This should return the minimal set of attributes required to create a valid
  # SheldonRatingScale. As you add validations to SheldonRatingScale, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SheldonRatingScalesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all sheldon_rating_scales as @sheldon_rating_scales" do
      sheldon_rating_scale = SheldonRatingScale.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sheldon_rating_scales).should eq([sheldon_rating_scale])
    end
  end

  describe "GET show" do
    it "assigns the requested sheldon_rating_scale as @sheldon_rating_scale" do
      sheldon_rating_scale = SheldonRatingScale.create! valid_attributes
      get :show, {:id => sheldon_rating_scale.to_param}, valid_session
      assigns(:sheldon_rating_scale).should eq(sheldon_rating_scale)
    end
  end

  describe "GET new" do
    it "assigns a new sheldon_rating_scale as @sheldon_rating_scale" do
      get :new, {}, valid_session
      assigns(:sheldon_rating_scale).should be_a_new(SheldonRatingScale)
    end
  end

  describe "GET edit" do
    it "assigns the requested sheldon_rating_scale as @sheldon_rating_scale" do
      sheldon_rating_scale = SheldonRatingScale.create! valid_attributes
      get :edit, {:id => sheldon_rating_scale.to_param}, valid_session
      assigns(:sheldon_rating_scale).should eq(sheldon_rating_scale)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SheldonRatingScale" do
        expect {
          post :create, {:sheldon_rating_scale => valid_attributes}, valid_session
        }.to change(SheldonRatingScale, :count).by(1)
      end

      it "assigns a newly created sheldon_rating_scale as @sheldon_rating_scale" do
        post :create, {:sheldon_rating_scale => valid_attributes}, valid_session
        assigns(:sheldon_rating_scale).should be_a(SheldonRatingScale)
        assigns(:sheldon_rating_scale).should be_persisted
      end

      it "redirects to the created sheldon_rating_scale" do
        post :create, {:sheldon_rating_scale => valid_attributes}, valid_session
        response.should redirect_to(SheldonRatingScale.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sheldon_rating_scale as @sheldon_rating_scale" do
        # Trigger the behavior that occurs when invalid params are submitted
        SheldonRatingScale.any_instance.stub(:save).and_return(false)
        post :create, {:sheldon_rating_scale => {}}, valid_session
        assigns(:sheldon_rating_scale).should be_a_new(SheldonRatingScale)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SheldonRatingScale.any_instance.stub(:save).and_return(false)
        post :create, {:sheldon_rating_scale => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sheldon_rating_scale" do
        sheldon_rating_scale = SheldonRatingScale.create! valid_attributes
        # Assuming there are no other sheldon_rating_scales in the database, this
        # specifies that the SheldonRatingScale created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SheldonRatingScale.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => sheldon_rating_scale.to_param, :sheldon_rating_scale => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested sheldon_rating_scale as @sheldon_rating_scale" do
        sheldon_rating_scale = SheldonRatingScale.create! valid_attributes
        put :update, {:id => sheldon_rating_scale.to_param, :sheldon_rating_scale => valid_attributes}, valid_session
        assigns(:sheldon_rating_scale).should eq(sheldon_rating_scale)
      end

      it "redirects to the sheldon_rating_scale" do
        sheldon_rating_scale = SheldonRatingScale.create! valid_attributes
        put :update, {:id => sheldon_rating_scale.to_param, :sheldon_rating_scale => valid_attributes}, valid_session
        response.should redirect_to(sheldon_rating_scale)
      end
    end

    describe "with invalid params" do
      it "assigns the sheldon_rating_scale as @sheldon_rating_scale" do
        sheldon_rating_scale = SheldonRatingScale.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SheldonRatingScale.any_instance.stub(:save).and_return(false)
        put :update, {:id => sheldon_rating_scale.to_param, :sheldon_rating_scale => {}}, valid_session
        assigns(:sheldon_rating_scale).should eq(sheldon_rating_scale)
      end

      it "re-renders the 'edit' template" do
        sheldon_rating_scale = SheldonRatingScale.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SheldonRatingScale.any_instance.stub(:save).and_return(false)
        put :update, {:id => sheldon_rating_scale.to_param, :sheldon_rating_scale => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sheldon_rating_scale" do
      sheldon_rating_scale = SheldonRatingScale.create! valid_attributes
      expect {
        delete :destroy, {:id => sheldon_rating_scale.to_param}, valid_session
      }.to change(SheldonRatingScale, :count).by(-1)
    end

    it "redirects to the sheldon_rating_scales list" do
      sheldon_rating_scale = SheldonRatingScale.create! valid_attributes
      delete :destroy, {:id => sheldon_rating_scale.to_param}, valid_session
      response.should redirect_to(sheldon_rating_scales_url)
    end
  end

end
